# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Master Your PPE"
  url = "#top"
  weight = 10

[[main]]
  name = "Vision"
  url = "#vision"
  weight = 20

 [[main]]
   name = "Team"
   url = "/team"
   weight = 40

 [[main]]
   name = "Filter Testing"
   url = "#testing"
   weight = 50

 [[main]]
   name = "Resources"
   url = "/trusted-resources"
   weight = 60
  
 [[main]]
   name = "Hey, wear your PPE!"
   url = "#top-main"
   weight = 70

 [[main]]
   name = "Why?"
   url = "#top-why"
   weight = 80

 [[main]]
   name = "Wait, how serious is this?"
   url = "#top-main"
   weight = 90

 [[main]]
   name = "What is really going on?"
   url = "#top-main"
   weight = 100

## [[main]]
##   name = "Updates"
##   url = "#updates"
##   weight = 65



[[main]]
  name = "Contact"
  url = "#contact"
  weight = 110

[[main_right]]
  name = "&nbsp; Wiki"
  url = "https://github.com/dickansj/MasterYourPPE/wiki"
  pre = "<i class='fab fa-github'></i>"
  weight = 120

## [[main_right]]
##  url = "https://www.twitter.com"
##  pre = "<i class='fab fa-twitter'></i>"
##  weight = 90
## Only one icon appearing

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
